<?php

use Symfony\Component\HttpFoundation;
use Symfony\Component\HttpFoundation\Request;

/**
 * Implements hook_theme().
 */
function custom_widget_theme($existing, $type, $theme, $path) {
  return [
    'sample_block' => [
      'variables' => ['data' => NULL]
    ],
  ];
}

/**
 * Implements hook_preprocess_template().
 */
function custom_widget_preprocess_sample_block(&$vars) {
  $vars['client_ip'] = \Drupal::request()->getClientIp();
}
